### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by ypawar159** [ra101/kissSolver#3]
Hey @ra101 
I have tried to crack the kissanime captcha twice and haven't found the solution yet.
You strategy of recognising the digits is what I planned to do at first.
The first idea was to gather all the images, recognise digits and use that to reduce the complexity of the problem.
I was using colour detection which obviously failed after first few images.
Another idea was to brute force the captcha page and get all the images with challenges, and then use probability to guess the labels for any image.
I was able to capture the data for 48 hours straight, so have lot of data. And if required can gather more.
I have 10 images for each generic image grouped as well. That would help in recreating a original image.
But the probability calculation is beyond my skills for now. Though some images I tried did provide at least two major labels which are correct.
I haven't tried your code yet but look like you are only detecting the digits in the images which does reduce the guess work but still not complete yet. I may be wrong here.
Ideal solution would be the one which can be retrained automatically if kissanime ever changes the images or digit superimpose logic.
Let me know if we can work on this to figure out some robust technique to deal with this captcha.
I really want this working so that I can be prepared for long hours internet outage ;) and it's fun to develop this project.

**Comment by ypawar159** [comment]
I just gave the extension a try and it works fine. For few challenges it tried to reload the page some times.
Could that be fixed by expanding the dataset of know images and labels?

**Comment by ypawar159** [comment]
Looks like chrome extension is loading the model.json and some shard.bin file from github for each captcha page.
Would definitely like to keep those files hosted locally as one of the configurable parameters. Otherwise github might ban my IP while I am downloading a long series like bleach or one piece. It did happen already with 502 errors for github hosted files.

**Comment by ypawar159** [comment]
After going through the docs I could say that there is lot of manual work involved in getting the dataset for training the digit recognition  model.
If the images ever change then that would required manually creating generic image for all the new images. I was trying to avoid manual work as much as possible.
Here are some ideas I have:
1. **Downloading images:** It's possible to download using the python requests/urllib. I have a working code for it.

2. **Make Generic images:** Using manual methods to do this is not scalable and will take lot of time. What if we have 10 numbers images of same original image, we can run a pixel to pixel similarity check and combine into new image where the most common values are found out of 10?. As long as the digits in the same image are at fairly different positions it should work.

3.  For image dimension there is a way to do without reading the complete file from the disk. I have a working code for it. Though it doesn't matter much given limited number of files to be processed.

4. **Numbers Extraction**: using magic wand, well good approach still requires processing all images manually. I had tried to use the colour recognition for this in my first try and it works most of the time. The observation is the colours used for digit are limited, so this works. One could also add some localisation algorithm for detecting the coloured digit or limiting the contour sizes to width/height.

**Comment by ypawar159** [comment]
Just checked my db, it has 4601 unique images and  211 unique labels.
Total images are 45900, this includes a single image with 0-9 digits superimposed.
There is clearly some improvements can be done on existing trained model by utilising this additional data (after pre-processing it smart way).

**Comment by ra101** [comment]
> I was able to capture the data for 48 hours straight, so have lot of data. And if required can gather more.
> I have 10 images for each generic image grouped as well. That would help in recreating a original image.

Kudos!

> Looks like chrome extension is loading the model.json and some shard.bin file from github for each captcha page.
> Would definitely like to keep those files hosted locally as one of the configurable parameters. Otherwise github might ban my IP while I am downloading a long series like bleach or one piece. It did happen already with 502 errors for github hosted files.

One has to host those files to work with. 'cuz simply using `fs` module does not work. I have tried it. so we have to host the file somewhere. local hosting would have been an overhead as code increases and also, each time captcha page is loaded, we first need to host those files, which takes some time. **You can try those methods again, I was pretty new in development back then**



> 1. **Downloading images:** It's possible to download using the python requests/urllib. I have a working code for it.

Ya now i know how to do this, i can add myself or u can contribute to this..


> 2. **Make Generic images:** Using manual methods to do this is not scalable and will take lot of time. What if we have 10 numbers images of same original image, we can run a pixel to pixel similarity check and combine into new image where the most common values are found out of 10?. As long as the digits in the same image are at fairly different positions it should work.

> 4. **Numbers Extraction**: using magic wand, well good approach still requires processing all images manually. I had tried to use the colour recognition for this in my first try and it works most of the time. The observation is the colours used for digit are limited, so this works. One could also add some localisation algorithm for detecting the coloured digit or limiting the contour sizes to width/height.

Once `Haar-cascade` recognizes the region for digit, we can use magic-wand in that region and remove that area, then a `bitwise_and` of all images would be able to generate a generic image.

> 3. For image dimension there is a way to do without reading the complete file from the disk. I have a working code for it. Though it doesn't matter much given limited number of files to be processed.

Well if we can automate, we should.


Tagline still needs a manual operation. if we can automate that, using the way you scaped all images would be a lot helpful.
I can make a CNN for categorizing image, so resolution won't be necessary anymore.

**Comment by ypawar159** [comment]
> Once Haar-cascade recognizes the region for digit, we can use magic-wand in that region and remove that area, then a bitwise_and of all images would be able to generate a generic image.

This magic wand could be done through scripting?

I had tried to host the files on localhost as well as s3 bucket. For localhost sometimes there is error due to non ssl url. And even with SSL of s3 sometimes there issue of CORS, as the files are not on the kissanime domain. There was one note on ts.js load model page, that the file fetching function could be overridden, so we could disable sec-fetch mode and try to get the file.
Another approach would be to put the required files in the extension itself, or in some js code. Loading a file from chrom-extension url doesn't work though. What if background script for the extension used? There is more freedom in background script than the content script. This way the required files could be loaded once the browser starts.


> Tagline still needs a manual operation. if we can automate that, using the way you scaped all images would be a lot helpful.
> I can make a CNN for categorizing image, so resolution won't be necessary anymore.

If we have each image tagged then we won't need a cnn. As we will be having almost complete DB used for the captcha.
So number recognition and tagging images are the only challenges for this.

**Comment by ypawar159** [comment]
Check this extension. It loads the tf model in the background script, and listens for messages to do the predictions.
Since background scripts are not limited by the loaded website domain, moving the prediction code to it could be useful, and might also allow local hosted non SSL resources to be accessed.

https://github.com/JK0N/tensorflow-image-recognition-chrome-extension/blob/master/src/background.js

**Comment by ra101** [comment]
Unfortunately, the curse of the year 2020, took down the website too. The project now archived in vain.
Thanks for the input tho.

**Comment by ypawar159** [comment]
Ahh, just visited the website and yes it's getting down. 😭
And here I was hoping to get some hands-on the AI stuff.
So which is the best alternative alive to this?

**Comment by ra101** [comment]
Well.. kissasian.sh is still there.. but it does not have much of a challenge.
